// <auto-generated />
using System;
using DocsVision.Monitoring.DataModel.Framework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DocsVision.Monitoring.DataModel.Framework.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20181015100322_KindFolderLinkUpdates")]
    partial class KindFolderLinkUpdates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocsVision.Monitoring.DataModel.KindFolderLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("FolderID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("1");

                    b.Property<Guid>("KindID");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("kindfolderlinks_pk_id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("KindFolderLinks","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
